# Numpy: Numeric computing library

NumPy (Numerical Python) is one of the core packages for numerical computing in Python. Pandas, Matplotlib, Statmodels and many other Scientific libraries rely on NumPy.

In [31]:
import sys
# import numpy
import numpy as np

In [ ]:
# pip install numpy 
# pip install pandas
# pip install matplotlib

# Basic Numpy Array

In [ ]:
# np.array([1, 2, 3, 4])

# variable = value

# arr = numpy.array([1,2,3,4])
arr = np.array([1,2,3,4])
# arr = np.array([1.,2.,3.,4.])
arr.dtype

In [ ]:
a = np.array([1, 2, 3, 4 ,5,6,7,8,9,10])
b = np.array([0, .5, 1, 1.5, 2])

In [ ]:
# a[0], a[1]
# a[0:]
# a[1:3]
# a[1:-1]

a[1:7]
b[0], b[2], b[3]
b[[0, 3,4]]

In [ ]:
# b[0], b[2], b[-1]
# b[[0, 2, -1]]

b

# Array Type

In [ ]:
a.dtype
b.dtype

In [ ]:
np.array([1, 2, 3, 4], dtype="float")
# np.array([1, 2, 3, 4], dtype="int32")

In [ ]:
c = np.array([1, 2, 3, 4])
c.dtype
c.astype("float")

# Dimension and Shape

In [ ]:
# A = np.array([
#     [1, 2, 3],
#     [4, 5, 6]
# ])

A = np.array([[1,2,3,4,5,6], [1,2,3,6,7,8,]])
# A = np.array([[[1,2,3,4,5,6], [1,2,3,6,7,8,]], [[1,2,3,4,5,6], [1,2,3,6,7,8,]]])
A

In [ ]:
# A.shape
# A.ndim
# A.size
A.shape
A.reshape
A.ndim
A.size

In [ ]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

In [ ]:
# B.shape
# B.ndim
# B.size

In [ ]:
C = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],[1,2]
    ]
])

In [ ]:
C.dtype
C.shape
C.size
type(C[0])

## Indexing and Slicing of Matrices

In [ ]:
# Square matrix
A = np.array([
#.   0. 1. 2
    [1, 2, 3], # 0
    [4, 5, 6], # 1
    [7, 8, 9]  # 2
])
A[0:,1:]


In [ ]:
# A[1]
# A[1][0]
# A[1, 0]
# A[0:2]

A[0][0]

In [ ]:
A[:, :2]
A[:2, :2]

In [ ]:
A[1] = np.array([10, 10, 10])
A[2] = 99

# Some Statistic

In [ ]:
"""
Other topic
    - sum
    - mean - average
    - median
    - variance
    - standard deviation
"""
a = np.array([1, 2, 3, 4])

In [ ]:
# a.sum()
# a.mean()
# a.std()
# a.var()
a.sum()
len(a)
a.mean()
a.var()
a.std()

In [ ]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [ ]:
# A.sum()
# A.mean()
# A.std()

A.sum()
# len(A)
A.mean()
A.std()

In [ ]:
A.sum(axis=1)
# A.sum(axis=0)
# A.mean(axis=0)
# A.std(axis=0)

# more: https://numpy.org/doc/stable/reference/arrays.ndarray.html#array-methods

## Broadcasting and Vectorized operations

In [ ]:
a = np.arange(4)
a = np.array([1, 2, 3, 4])
a - 10

In [ ]:
a + 10
a * 10
a += 100

In [ ]:
l = [0, 1, 2, 3]
[i * 10 for i in l]

In [ ]:
a = np.arange(4)
b = np.array([10, 10, 10, 10])

In [ ]:
a + b
a * b

# Boolean Arrays

In [ ]:
a = np.arange(4)
a = np.array([1,2,3,4])

# ~ -> not
# | -> or
# & -> and

In [ ]:
# a[0], a[-1]
# a[[0, -1]]
# a[[True, False, False, True]]
# a >= 2
# a[a >= 2]
# a[a > a.mean()]
# a[~(a > a.mean())]
a[(a == 0) | (a == 1)] # ==> 0,1
a[(a <= 2) & (a % 2 == 0)] # ==> 0,2

# a = np.array([1,2,3,4])
# a > 2
# # a[[False, False,  True,  True]]
# a[[False, False,  True,  True]]

a[a>2] 

# size

In [ ]:
# An integer in Python is > 24bytes
sys.getsizeof(1)

In [ ]:
# Longs are even larger
sys.getsizeof(10**100)

In [ ]:
# Numpy size is much smaller
np.dtype(int).itemsize

In [ ]:
# Numpy size is much smaller
np.dtype(np.int8).itemsize

In [ ]:
np.dtype(float).itemsize

In [ ]:
# Lists are even larger
# A one-element list
sys.getsizeof([1])

In [ ]:
# An array of one element in numpy
np.array([1]).nbytes

In [ ]:
# And performance is also important

In [32]:
l = list(range(10000000))
a = np.arange(10000000)

In [33]:
%time np.sum(a ** 2)
# magic method

CPU times: total: 31.2 ms
Wall time: 35.3 ms


-1039031360

In [34]:
%time sum([x ** 2 for x in l])

CPU times: total: 1.08 s
Wall time: 1.1 s


333333283333335000000

## Useful Numpy functions

### `random` 

In [66]:
# np.random.random(size=2)
# np.random.normal(size=2)
# np.random.rand(2, 4)
np.random.seed(1)
np.random.random([3,5])
np.random.randint(0,10,[3,5])

array([[2, 4, 7, 7, 9],
       [1, 7, 0, 6, 9],
       [9, 7, 6, 9, 1]])

### `arange` 

In [71]:
# np.arange(10)
# np.arange(5, 10)
# np.arange(0, 1, .1)

np.arange(1,10,2)

array([1, 3, 5, 7, 9])

### `reshape`

In [77]:
# np.arange(10).reshape(2, 5)
# np.arange(10).reshape(5, 2)

np.arange(15).reshape(3,5)

ValueError: cannot reshape array of size 15 into shape (3,4)

### `linspace`

In [80]:
# np.linspace(0, 1, 5)
# np.linspace(0, 1, 20)
# np.linspace(0, 1, 20, False)

np.linspace(0,1,5)
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

### `zeros`, `ones`, `empty`

In [83]:
# np.zeros(5)
# np.zeros((3, 3))
# np.zeros((3, 3), dtype=np.int)

np.zeros([3,5])
np.ones([3,5])
np.full([3,5], 9999)

array([[9999, 9999, 9999, 9999, 9999],
       [9999, 9999, 9999, 9999, 9999],
       [9999, 9999, 9999, 9999, 9999]])

In [ ]:
np.ones(5)

In [ ]:
np.full([3,5],10)

In [ ]:
np.empty(5)
np.empty((2, 2))

In [ ]:
### `identity` and `eye`

In [ ]:
np.identity(3)

In [ ]:
np.eye(3, 3)

In [ ]:
np.eye(8, 4, k=1)

In [ ]:
np.eye(8, 4, k=-3)

In [ ]:
"Hello World"[6]